package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer categoryid;
     private String categoryname;

    public Category() {
    }

    public Category(String categoryname) {
       this.categoryname = categoryname;
    }
   
    public Integer getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }
    public String getCategoryname() {
        return this.categoryname;
    }
    
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }




}


