package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer commentsid;
     private int vid;
     private int uid;
     private String posts;

    public Comments() {
    }

    public Comments(int vid, int uid, String posts) {
       this.vid = vid;
       this.uid = uid;
       this.posts = posts;
    }
   
    public Integer getCommentsid() {
        return this.commentsid;
    }
    
    public void setCommentsid(Integer commentsid) {
        this.commentsid = commentsid;
    }
    public int getVid() {
        return this.vid;
    }
    
    public void setVid(int vid) {
        this.vid = vid;
    }
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public String getPosts() {
        return this.posts;
    }
    
    public void setPosts(String posts) {
        this.posts = posts;
    }




}


