package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Designation generated by hbm2java
 */
public class Designation  implements java.io.Serializable {


     private Integer designationid;
     private String designationname;

    public Designation() {
    }

    public Designation(String designationname) {
       this.designationname = designationname;
    }
   
    public Integer getDesignationid() {
        return this.designationid;
    }
    
    public void setDesignationid(Integer designationid) {
        this.designationid = designationid;
    }
    public String getDesignationname() {
        return this.designationname;
    }
    
    public void setDesignationname(String designationname) {
        this.designationname = designationname;
    }




}


