package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Forums generated by hbm2java
 */
public class Forums  implements java.io.Serializable {


     private Integer forumid;
     private int uid;
     private String question;
     private Integer status;
     private String ftitle;
     private String ondate;

    public Forums() {
    }

	
    public Forums(int uid, String question, String ftitle) {
        this.uid = uid;
        this.question = question;
        this.ftitle = ftitle;
    }
    public Forums(int uid, String question, Integer status, String ftitle, String ondate) {
       this.uid = uid;
       this.question = question;
       this.status = status;
       this.ftitle = ftitle;
       this.ondate = ondate;
    }
   
    public Integer getForumid() {
        return this.forumid;
    }
    
    public void setForumid(Integer forumid) {
        this.forumid = forumid;
    }
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getFtitle() {
        return this.ftitle;
    }
    
    public void setFtitle(String ftitle) {
        this.ftitle = ftitle;
    }
    public String getOndate() {
        return this.ondate;
    }
    
    public void setOndate(String ondate) {
        this.ondate = ondate;
    }




}


