package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Likesdis generated by hbm2java
 */
public class Likesdis  implements java.io.Serializable {


     private Integer id;
     private int vid;
     private int uid;
     private Integer likes;
     private Integer dislikes;

    public Likesdis() {
    }

	
    public Likesdis(int vid, int uid) {
        this.vid = vid;
        this.uid = uid;
    }
    public Likesdis(int vid, int uid, Integer likes, Integer dislikes) {
       this.vid = vid;
       this.uid = uid;
       this.likes = likes;
       this.dislikes = dislikes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getVid() {
        return this.vid;
    }
    
    public void setVid(int vid) {
        this.vid = vid;
    }
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public Integer getLikes() {
        return this.likes;
    }
    
    public void setLikes(Integer likes) {
        this.likes = likes;
    }
    public Integer getDislikes() {
        return this.dislikes;
    }
    
    public void setDislikes(Integer dislikes) {
        this.dislikes = dislikes;
    }




}


