package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private Integer ratingid;
     private int vid;
     private int uid;
     private int rating;

    public Rating() {
    }

    public Rating(int vid, int uid, int rating) {
       this.vid = vid;
       this.uid = uid;
       this.rating = rating;
    }
   
    public Integer getRatingid() {
        return this.ratingid;
    }
    
    public void setRatingid(Integer ratingid) {
        this.ratingid = ratingid;
    }
    public int getVid() {
        return this.vid;
    }
    
    public void setVid(int vid) {
        this.vid = vid;
    }
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }




}


