package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Replys generated by hbm2java
 */
public class Replys  implements java.io.Serializable {


     private Integer replyid;
     private int uid;
     private String reply;
     private Integer ref;
     private String ondate;

    public Replys() {
    }

	
    public Replys(int uid, String reply) {
        this.uid = uid;
        this.reply = reply;
    }
    public Replys(int uid, String reply, Integer ref, String ondate) {
       this.uid = uid;
       this.reply = reply;
       this.ref = ref;
       this.ondate = ondate;
    }
   
    public Integer getReplyid() {
        return this.replyid;
    }
    
    public void setReplyid(Integer replyid) {
        this.replyid = replyid;
    }
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    public String getReply() {
        return this.reply;
    }
    
    public void setReply(String reply) {
        this.reply = reply;
    }
    public Integer getRef() {
        return this.ref;
    }
    
    public void setRef(Integer ref) {
        this.ref = ref;
    }
    public String getOndate() {
        return this.ondate;
    }
    
    public void setOndate(String ondate) {
        this.ondate = ondate;
    }




}


