package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Userdetails generated by hbm2java
 */
public class Userdetails  implements java.io.Serializable {


     private Integer uid;
     private String username;
     private String email;
     private String password;
     private Integer desgnation;

    public Userdetails() {
    }

	
    public Userdetails(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }
    public Userdetails(String username, String email, String password, Integer desgnation) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.desgnation = desgnation;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getDesgnation() {
        return this.desgnation;
    }
    
    public void setDesgnation(Integer desgnation) {
        this.desgnation = desgnation;
    }




}


