package POJO;
// Generated Nov 29, 2013 11:00:15 AM by Hibernate Tools 3.2.1.GA



/**
 * Video generated by hbm2java
 */
public class Video  implements java.io.Serializable {


     private Integer videoid;
     private Integer categoryid;
     private String title;
     private String videopath;
     private String description;

    public Video() {
    }

	
    public Video(String title, String videopath, String description) {
        this.title = title;
        this.videopath = videopath;
        this.description = description;
    }
    public Video(Integer categoryid, String title, String videopath, String description) {
       this.categoryid = categoryid;
       this.title = title;
       this.videopath = videopath;
       this.description = description;
    }
   
    public Integer getVideoid() {
        return this.videoid;
    }
    
    public void setVideoid(Integer videoid) {
        this.videoid = videoid;
    }
    public Integer getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getVideopath() {
        return this.videopath;
    }
    
    public void setVideopath(String videopath) {
        this.videopath = videopath;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


